import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Choose hopping type</h1>
        <div>
          <h2>With Form</h2>
          <ul>
            <li><a href="/with-form/page_a">Page A</a></li>
            <li><a href="/with-form/page_b">Page B</a></li>
          </ul>
        </div>
        {/* <div>
          <h2>With SPA Routing</h2>
          <ul>
            <li><a href="/with-spa/page_a">Page A</a></li>
            <li><a href="/with-spa/page_b">Page B</a></li>
          </ul>
        </div> */}
      </main>
    </>
  )
}
